# Generated by Django 4.1 on 2022-08-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cod_seot', models.CharField(max_length=50)),
                ('cod_forcebeat', models.CharField(max_length=50)),
                ('cod_scm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('cod_fb_tecnico', models.CharField(max_length=50)),
                ('cod_seot_tecnico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
            },
        ),
        migrations.CreateModel(
            name='SolMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cod_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.recurso')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.tecnico')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Material',
            },
        ),
    ]
