# Generated by Django 4.1 on 2022-08-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solmaterial',
            options={'verbose_name': 'Solicitud de Material Por Tecnico', 'verbose_name_plural': 'Solicitudes de Material Por Tecnico'},
        ),
        migrations.RemoveField(
            model_name='solmaterial',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solmaterial',
            name='cod_material',
        ),
        migrations.RemoveField(
            model_name='solmaterial',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='SolMaterialChoises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.recurso')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.solmaterial')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Material',
            },
        ),
    ]
