# Generated by Django 4.1 on 2022-08-12 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterial',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solmaterial',
            name='fecha',
        ),
        migrations.AddField(
            model_name='solmaterial',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solmaterial',
            name='cod_material',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SolMaterialChoises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cod_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.solmaterial')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Material',
            },
        ),
    ]
