# Generated by Django 4.1 on 2022-08-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_remove_solmaterial_fecha_solmaterial_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterial',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solmaterial',
            name='cod_material',
        ),
        migrations.CreateModel(
            name='SolMaterialChoises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cod_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.solmaterial')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Material',
            },
        ),
    ]
