# Generated by Django 4.1 on 2022-08-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_solmaterial_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterial',
            name='cod_material',
        ),
    ]
