# Generated by Django 4.1 on 2022-08-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_remove_solmaterial_cod_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterial',
            name='materiales',
        ),
        migrations.AddField(
            model_name='solmaterialchoises',
            name='materiales',
            field=models.ManyToManyField(to='almacen.recurso'),
        ),
    ]
