# Generated by Django 4.1 on 2022-08-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_remove_solmaterial_materiales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterialchoises',
            name='materiales',
        ),
        migrations.AddField(
            model_name='solmaterialchoises',
            name='materiales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.recurso'),
            preserve_default=False,
        ),
    ]
