# Generated by Django 4.1 on 2022-08-14 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_remove_solmaterialchoises_materiales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solmaterial',
            options={'verbose_name': 'Solicitud de Material Por Tecnico', 'verbose_name_plural': 'Solicitudes de Material Por Tecnico'},
        ),
        migrations.RemoveField(
            model_name='solmaterial',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='solmaterialchoises',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
