# Generated by Django 4.1 on 2022-08-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_solmaterial_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solmaterialchoises',
            old_name='materiales',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='solmaterialchoises',
            old_name='cod_material',
            new_name='tecnico',
        ),
    ]
