# Generated by Django 4.1 on 2022-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_rename_materiales_solmaterialchoises_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterialchoises',
            name='material',
        ),
        migrations.AddField(
            model_name='solmaterialchoises',
            name='material',
            field=models.ManyToManyField(related_name='material', to='almacen.recurso', verbose_name='Material'),
        ),
    ]
