# Generated by Django 4.1 on 2022-08-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_remove_solmaterialchoises_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solmaterialchoises',
            name='material',
        ),
        migrations.AddField(
            model_name='solmaterialchoises',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='almacen.recurso', verbose_name='Material'),
            preserve_default=False,
        ),
    ]
